# fly.toml app configuration file generated for eagprox on 2024-03-20T21:05:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eagprox'
primary_region = 'arn'

[build]


[[vm]]
  size = 'shared-cpu-1x'
